/* =====================================================================
   NOIR Studio — Nathan's Knowledge Base (offline)
   Compiled from deep multi-source research. Each entry: id, keywords
   (what a user might type), title, level, content (plain, accurate).
   Nathan wraps these in his own brutal voice at runtime.
   ===================================================================== */
window.NoirKB = (window.NoirKB || []).concat([
  /* ---------- Psychoacoustics: why music pleases the ear/brain ---------- */
  {"id":"harmonic-series-basics","keywords":["harmonic series","overtones","why notes sound related","partials","timbre"],"title":"The Harmonic Series","level":"beginner","content":"Any vibrating string or air column produces a fundamental pitch plus quieter overtones at whole-number multiples (2x, 3x, 4x...). Those overtones are the octave, fifth, and major third above the fundamental, which is why those intervals feel naturally connected to the root. The harmonic series is the physics underneath nearly every rule about consonance and chord building."},
  {"id":"consonance-frequency-ratios","keywords":["consonance","why octaves sound good","simple ratios","octave fifth third","stable intervals"],"title":"Why Simple Ratios Sound Consonant","level":"beginner","content":"Intervals built on simple frequency ratios sound stable: octave (2:1), perfect fifth (3:2), perfect fourth (4:3), major third (5:4). When two tones share a simple ratio their overtones line up and reinforce instead of clashing. The simpler the ratio, the more restful the interval — which is why octaves and fifths anchor music worldwide."},
  {"id":"dissonance-roughness","keywords":["dissonance","why some notes clash","roughness","beating","critical band"],"title":"Dissonance and Roughness","level":"intermediate","content":"Dissonance largely comes from roughness: when two tones are close enough that their overtones fall within the ear's critical band, they beat against each other and feel unstable. Minor seconds and tritones are dissonant because their partials don't align. Dissonance isn't bad — it creates tension that makes returning to consonance feel rewarding."},
  {"id":"two-roots-of-consonance","keywords":["harmonicity","why consonance","neural","fusion","perception of pitch"],"title":"Harmonicity vs Roughness","level":"advanced","content":"Consonance has two mechanisms. Harmonicity: consonant combinations fit one harmonic series so the brain fuses them into a clear pitch. Roughness: dissonant combos have overtones that beat within the critical band. Listener preference tracks harmonicity strongly — the brain rewards sounds it can resolve into a clean fundamental."},
  {"id":"tension-and-release","keywords":["tension and release","resolution","why music feels satisfying","build up","payoff"],"title":"Tension and Release","level":"beginner","content":"Most musical satisfaction is a cycle: build tension, then resolve it. Dissonance, rhythmic instability, and harmonic motion away from home create tension; returning to consonance and the tonic releases it. Music with no tension feels flat; music that never resolves feels frustrating. The art is in the timing of the payoff."},
  {"id":"dominant-tonic-resolution","keywords":["dominant to tonic","v-i","authentic cadence","why does it sound finished","resolution chord"],"title":"Why Dominant→Tonic Feels Final","level":"intermediate","content":"The V chord contains a tritone plus the leading tone, both unstable. When V moves to I, the leading tone rises a half-step to the tonic and the tritone collapses inward like a rubber band snapping back. This voice-leading gravity is why a V–I cadence sounds like a finished sentence and is the strongest way to end a phrase."},
  {"id":"leading-tone-pull","keywords":["leading tone","seventh scale degree","ti to do","half step pull","melodic tension"],"title":"The Pull of the Leading Tone","level":"intermediate","content":"The seventh degree (ti) sits a half-step below the tonic and strongly 'wants' to rise to it. Ending on the leading tone feels incomplete; resolving up to the tonic gives closure. Hover on ti to build expectation, then land on do for release."},
  {"id":"huron-itpra-expectation","keywords":["expectation","huron","prediction","sweet anticipation","why prediction matters"],"title":"Huron's ITPRA Theory of Expectation","level":"advanced","content":"David Huron models musical emotion as five responses: Imagination, Tension, Prediction, Reaction, Appraisal. Pleasure comes partly from making accurate predictions (a built-in reward) and partly from being surprised in a safe context. Good music sets up expectations, then confirms or playfully violates them."},
  {"id":"prediction-surprise-pleasure","keywords":["surprise","predictability","why catchy","sweet spot","not too simple not too complex"],"title":"The Prediction–Surprise Sweet Spot","level":"intermediate","content":"The brain rewards correct predictions, so totally predictable music is boring and totally random music is unsatisfying. The pleasure zone is mostly-predictable with well-placed surprises. A melody that mostly does what you expect, then occasionally veers, keeps the prediction system engaged."},
  {"id":"dopamine-chills","keywords":["chills","frisson","goosebumps","dopamine","why music gives me chills"],"title":"Chills and the Dopamine Reward","level":"advanced","content":"Music triggers dopamine in two stages: the caudate during anticipation (the build-up) and the nucleus accumbens at the peak. Same reward circuit as food and money. Chills usually hit at expectation violations or sudden resolutions — the anticipation matters as much as the climax."},
  {"id":"mere-exposure-effect","keywords":["mere exposure","why songs grow on me","familiarity","repeated listening","like more over time"],"title":"The Mere Exposure Effect","level":"beginner","content":"We tend to like things more from repeated encounters. Repeated listening makes a piece easier to process, and the brain misreads that fluency as liking. That's why songs grow on you and radio repetition drives hits — until over-familiarity flips it to fatigue."},
  {"id":"repetition-power","keywords":["repetition","why repeat","hooks","margulis","on repeat"],"title":"Why Repetition Makes Music Feel Like Music","level":"intermediate","content":"Repetition pulls listeners from passive hearing into active participation — we mentally sing along and anticipate. Repeating a phrase makes even random sounds feel musical. It's the most reliable tool for making a hook stick, because it turns listening into something you do."},
  {"id":"repetition-vs-variation","keywords":["repetition vs variation","how much repetition","keep it interesting","motif development","balance"],"title":"Balancing Repetition and Variation","level":"intermediate","content":"Repeat enough that a motif is recognizable, then vary it just enough to refresh attention — change one note, the rhythm, the harmony underneath, or the register. A common pattern is repeat-repeat-vary (AAB): state an idea, repeat it, then answer it differently."},
  {"id":"stepwise-motion","keywords":["stepwise motion","conjunct","smooth melody","singable","easy to sing"],"title":"Stepwise Motion Sings Best","level":"beginner","content":"Melodies that move mostly by step are smooth, singable, and memorable — memorable tunes are roughly 75% steps, 25% leaps. Steps give flow; reserve leaps for emphasis. If a melody feels jumpy, smoothing it toward stepwise motion usually helps."},
  {"id":"gap-fill-leaps","keywords":["leap then step","gap fill","big jump in melody","after a leap","melodic leaps"],"title":"Follow Leaps with Steps (Gap-Fill)","level":"intermediate","content":"A large leap creates a 'gap' the ear wants filled. Leaps sound best followed by stepwise motion in the opposite direction, returning toward the center of the range. Leap up then step back down (or vice versa) — one of the most natural melodic shapes."},
  {"id":"melodic-contour-arch","keywords":["contour","arch shape","melodic shape","rise and fall","memorable melody"],"title":"Melodic Contour and the Arch","level":"intermediate","content":"Contour — the up/down shape — is what listeners remember most, often more than exact pitches. The arch (rise to a peak, then fall) is the most satisfying shape. Give each phrase a clear high point and let it settle; a distinctive contour makes a tune recognizable when hummed."},
  {"id":"chord-tones-strong-beats","keywords":["chord tones","strong beats","landing notes","downbeat","what note to land on"],"title":"Land on Chord Tones on Strong Beats","level":"intermediate","content":"Notes on strong beats (especially beat 1) are heard as important, so they should usually be chord tones — root, third, or fifth of the current chord. Passing/neighbor notes work on weak beats. Aligning strong melodic moments with chord tones keeps a melody grounded."},
  {"id":"phrase-length-breath","keywords":["phrase length","phrasing","breath","four bar phrase","question and answer"],"title":"Phrase Length and Breathing","level":"intermediate","content":"Melodies group into phrases, usually 2, 4, or 8 bars, mirroring breath and speech. Phrases often work as question-and-answer: the first feels open, the second answers and closes. Small rests between phrases let the listener breathe and make the melody conversational."},
  {"id":"tessitura-range","keywords":["tessitura","range","too high too low","comfortable range","vocal range"],"title":"Tessitura and Comfortable Range","level":"intermediate","content":"Tessitura is where a melody mostly sits. Keeping the bulk in a comfortable middle register makes it singable; occasional high notes create excitement. Save your highest notes for climaxes — a melody living at its extremes is tiring and hard to sing along to."},
  {"id":"groove-entrainment","keywords":["groove","entrainment","why i want to move","tap my foot","feel the beat"],"title":"Groove and Entrainment","level":"beginner","content":"Entrainment is the brain locking onto a steady pulse and synchronizing — why we tap our feet. A clear, regular beat gives a reliable framework to predict and move with. Groove is the pleasurable urge to move when that pulse is steady but not robotically rigid."},
  {"id":"syncopation-sweet-spot","keywords":["syncopation","off beat","why funk feels good","rhythmic tension","groove"],"title":"The Syncopation Sweet Spot","level":"intermediate","content":"The urge to move peaks at moderate syncopation — accents slightly off the expected beat. Too little is metronomic; too much breaks the pulse. Medium syncopation opens gaps the listener fills by moving to the implied beat — that's the pleasure."},
  {"id":"steady-pulse-plus-tension","keywords":["steady pulse","rhythmic tension","push and pull","beat tension","human feel"],"title":"Steady Pulse Plus Slight Tension","level":"intermediate","content":"Great grooves combine a rock-solid pulse with small tensions against it — syncopation, swing, micro-timing. The pulse lets the listener lock in; the deviations keep it alive. Quantizing everything perfectly to the grid often kills the groove."},
  {"id":"meter-and-accent","keywords":["meter","time signature","downbeat","strong and weak beats","4/4"],"title":"Meter and the Accent Hierarchy","level":"beginner","content":"Meter groups beats into strong/weak patterns (4/4 emphasizes 1 and 3, with 1 strongest). This hierarchy creates expectations about where accents fall. Notes on strong beats feel grounded; accenting weak beats creates the tension that drives syncopation."},
  {"id":"major-minor-emotion","keywords":["major minor","happy sad","why minor sounds sad","mode emotion","key feeling"],"title":"Major Sounds Happy, Minor Sounds Sad","level":"beginner","content":"Across many cultures major reads bright/happy and minor darker/sad, partly because the modes resemble the pitch patterns of happy vs sad speech. It's a strong tendency, not a law — tempo, timbre, and lyrics can override it. Use it as a default, not a rule."},
  {"id":"emotion-caveats","keywords":["mode caveats","not always sad","tempo confound","minor key happy","exceptions"],"title":"Caveats on Mode and Emotion","level":"advanced","content":"The major-happy/minor-sad mapping is easily confounded by tempo, loudness, articulation, and timbre, which often carry more emotional weight than mode. Fast minor-key music can sound energetic, not sad. Treat mode as one lever among several."},
  {"id":"tempo-emotion","keywords":["tempo","fast slow music","energy","bpm emotion","why fast music feels happy"],"title":"Tempo Shapes Felt Energy","level":"beginner","content":"Tempo is a powerful, cross-cultural emotional cue: faster feels energetic/exciting/happy, slower feels calm/serious/sad, often outweighing mode. The same melody changes character dramatically just by changing speed."},
  {"id":"timbre-emotion","keywords":["timbre","tone color","instrument sound","bright dark sound","why distortion sounds aggressive"],"title":"Timbre and Emotional Color","level":"intermediate","content":"Timbre shapes emotion independent of notes. Bright/harsh/distorted timbres (lots of high overtones and roughness) read as tense or aggressive; soft, warm, smooth timbres read as gentle. The right sound can convey emotion more directly than the melody."},
  {"id":"hook-design","keywords":["hook","catchy","earworm","how to write a hook","memorable"],"title":"Designing a Hook That Sticks","level":"intermediate","content":"A strong hook is short, repeated, and easy to sing: a distinctive rhythm, a clear contour, a few notes that mostly move by step in a comfortable range. Repetition plus mere-exposure lodges it in memory; a small surprise keeps it fresh. Aim for something reproducible after one or two hearings."},
  {"id":"songwriting-rules-of-thumb","keywords":["songwriting rules","proven tips","make melody catchy","practical melody","what works"],"title":"Proven Melodic Rules of Thumb","level":"intermediate","content":"Keep ~75% stepwise motion and follow leaps with steps; give each phrase a clear high point; land important notes on chord tones on strong beats; repeat a motif then vary it; stay mostly in a comfortable range; build tension and resolve on time; end strong phrases V–I; keep the hook short. Break these only on purpose."},
  {"id":"chord-progression-pleasure","keywords":["chord progression","why these chords","common progressions","i iv v vi","progression that works"],"title":"Why Common Progressions Work","level":"intermediate","content":"Progressions like I–V–vi–IV and I–IV–V endure because they balance departure and return: leave the tonic for mild tension, pass through chords that share notes (smooth voice leading), and resolve home, with V pulling hardest back to I. Familiar motion lets listeners predict and enjoy the resolution."},
  {"id":"resolution-timing","keywords":["resolution timing","delay resolution","build anticipation","hold the tension","when to resolve"],"title":"Timing the Resolution","level":"advanced","content":"Delaying an expected resolution — holding a dominant, suspending a note, extending a build — heightens pleasure because the anticipation itself releases dopamine. But delay too long and the listener loses the thread. Stretch tension to just before breaking, then deliver."},
  {"id":"surprise-techniques","keywords":["surprise","deceptive cadence","unexpected chord","plot twist","keep it interesting"],"title":"Using Surprise Deliberately","level":"advanced","content":"Controlled expectation violations create memorable moments: a deceptive cadence (V→vi), a borrowed chord, a sudden register jump, a rhythmic displacement. They work because the brain predicted something else and the music safely subverts it. Use sparingly, against a predictable backdrop."},
  {"id":"silence-and-space","keywords":["silence","rests","space in music","less is more","negative space"],"title":"The Power of Silence and Space","level":"intermediate","content":"Rests are active tools. Silence creates anticipation, frames the notes around it, and gives the listener room to predict. A pause before a hook can hit harder than more notes. Crowding every beat kills contrast; space makes what remains matter."}
]);

/* The rest of Nathan's brain — music theory + songwriting, and instrument
   mechanics + guitar troubleshooting — is loaded from JSON compiled by deep
   research. We merge it into window.NoirKB. The psychoacoustics set above is
   always available even if these fetches fail (e.g. opened via file://). */
window.NoirKBReady = Promise.all([
  fetch("music-teacher-kb.json").then((r) => (r.ok ? r.json() : [])).catch(() => []),
  fetch("music-teacher-knowledge.json").then((r) => (r.ok ? r.json() : [])).catch(() => []),
]).then((parts) => {
  parts.forEach((arr) => { if (Array.isArray(arr)) window.NoirKB = window.NoirKB.concat(arr); });
  return window.NoirKB;
});

